book_your_stay="預訂住宿"
check_in_validation="入住日期不能在退房日期之後！";
select_check_in="請選擇入住日期"
select_check_out="請選擇退房日期"
error_while_sending="發送電子郵件時出錯。"
date_format="日期格式"
booking_status_confirmed="預訂狀態已更改為已確認！"

booking_confirmation_message="Dear {NAME},
您的預訂 {BOOKING_DETAILS} 現已確認。
預訂確認碼: {BOOKING_CODE}
付費金額 : {PRICE} $ETH
付費方式為乙太幣請匯入此帳戶 : 0x989C06df5EdD08D88C77E8C14DE048f241A6D8F8
如果您有任何其他問題，請隨時與我們聯繫。
乙太幣付款交易說明>> https://amy.com/wordpress/2019/07/10/付款交易說明/
乙太幣交易過程查詢>> http://amy.com:8000/
＝＝＝＝＝＝＝＝＝＝＝＝＝＝
AMY Hotel
電話：04-22299668
地址 : 台中市北區三民路三段999號
Email：amy@mail.amy.com
＝＝＝＝＝＝＝＝＝＝＝＝＝＝"

testcode="{BOOKING_CODE}"


booking_has_confirmed="Your booking has been confirmed!您的預訂已確認！"

send_message="Send Message"
message_customer="Confirm booking and send message to customer"
confirm_booking="確認預訂"
code="Code"
confirm="確認"
new_bookings="新預訂"
confirmed_bookings="確認預訂"
receive_booking_confirmed="謝謝。 確認預訂後，您會收到一封電子郵件。";
no_availability_selected_dates="很抱歉，在您所選日期沒有此房型的空房情況。"
customer="Customer"
room="Room"
confirmed_bookings="確認預訂"
new_bookings="新預訂"
price_for="價格"
nights="夜"
new_booking_notification="New Booking Notification"
remarks="備註"
remarks_requirements="請在下面輸入任何評論"
please_enter_contact="請輸入您的聯繫方式"
your_name="Your Name"
book_now="立即預定"
please_select_room="請選擇您的房間"
search="搜尋"
check_out_date="離開日期"
check_in_date="入住日期"
guests="人數"
enter_dates_availability="請輸入您的住宿日期以查詢空房情況"
double_room_ground="Ex. Double Room on the ground floor"
price_night="Price per night"
available_rooms="Available Rooms"
add="Add"
max_persons="Maximum Persons"
bookings="Bookings"
manage_rooms="管理客房";
no_results = "在選定的時間段內找不到可用的房間。"
advertisements = "Advertisements"
refine_results = "Refine Results"
keyword = "Keyword"
price_range = "Price Range"
yes_word = "Yes"
no_word = "No"
submit = "Submit"
our_ads = "Our classified ads"
search_results = "Search Results"
results_format = "Results Format"
price = "價格"
details = "詳情"
go_back = "Go Back"
wrong_code = "Wrong image code!"
sent_by = "Sent by";
phone = "聯絡電話"
email = "信箱"
message_or_questions = "請在下面輸入您的信息或問題"
subject = "主旨"
message = "內容"
your_details = "您的資料"
name= "姓名"
please_enter_code = "Please enter the code"
send = "發送"
home_link = "首頁"
contact_link = "聯繫"
message_sent_success = "Your message has been sent successfully"
admin_panel = "管理頁面"
login_to_continue = "請登錄訪問更多內容"
username = "UserName"
password = "Password"
login = "Login"
config_options = "Configuration Options"
save = "Save"
new_password = "New Password"
modify_admin_user_pass="Modify the Admin Username & Password"
manage_listings = "Manage your rooms"
add_new_listing = "New Room Type"
your_current_listings = "Current room types"
edit = "Edit"
images = "Images"
title = "Name"
description = "Description"
delete = "Delete"
modify_images = "Modify the room images"
new_added_success = "The new room type has been added successfully!"
add_another = "Add another one"
or_message = "or"
listing_details = "Room Details"
please_select = "Please Select"
edit_listing = "Edit the room information"
modify = "Modify"
upload_more_images = "Upload more images"
website_settings = "Website Settings"
use_seo_urls = "Use SEO urls"
currency = "Currency"
results_per_page = "Results per Page"
admin_email = "Admin Email Address"
use_captcha_images = "Use Captcha Images"
sure_to_delete = "Are you sure that you would like to delete these rooms?"
old_password = "Old Password"
confirm_new_password = "Confirm New Password"
passwords_mismatch = "The 2 new passwords mismatch!"
old_password_wrong = "The old password you entered is wrong!"
password_changed_success = "The password has been changed successfully!";
open_main_site = "OPEN THE MAIN SITE"
settings = "Settings"
logout = "LOGOUT"
help_docs = "HELP & DOCS"
have_questions = "有疑問嗎？"
modifications_saved = "The new values have been saved successfully!"